### PR TITLE
parse return struct defs

### PR DESCRIPTION
**Pull request by Riedlers-sockpuppet**
mainly so I don't have to scatter struct defs all over the place

- - -
This change is [Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/53)

### CODE REVIEW

**Comment by Riedlers-sockpuppet** [comment]
just noticed a TODO: detecting `multiple_structure` inside the current file and loading `structure()` from the other file

**Review by mcquenji — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/53#-:-NjIQ_iq9ocpw0aPzFwc:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @mkocagoel)

**Review by mcquenji — COMMENTED** [review]
> just noticed a TODO: detecting `multiple_structure` inside the current file and loading `structure()` from the other file

yeah  i don't think we have  a `strucutre()` inside a `multiple_structure`, so i'd implemenet the parsing for that once we do.

> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/53#-:-NjIRMl8CSMnlmPFOSd7:b-wem442)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @mkocagoel)

**Comment by mcquenji** [comment]
skipping review from @mkocagoel as he has nothing to do with the python script

**Comment by Riedlers-sockpuppet** [comment]
> yeah i don't think we have a `strucutre()` inside a `multiple_structure`, so i'd implemenet the parsing for that once we do.

we do

**Pull request merged**
