### PR TITLE
LP-191 cleanup api returns

### PR DESCRIPTION
**Pull request by Riedlers-sockpuppet**
turns out, we were returning the *entire* plan almost every time we changed anything about it, even if the client is just inserting new info. das not good

- - -
This change is [Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/56)

### CODE REVIEW

**Comment by Riedlers-sockpuppet** [comment]
oh yea um, this depends on #49 so ignore the rat's tail of merge conflict here

edit: actually just wait for #49 to be merged so I can rebase and make github recognize the actual changes

**Review by Muhiiii — COMMENTED** [review]
> Reviewed 2 of 9 files at r1, 23 of 25 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/56)* status: 25 of 27 files reviewed, 1 unresolved discussion (waiting on @mcquenji and @Riedlers-sockpuppet)

___
*[`lbplanner/classes/helpers/plan_helper.php` line 126 at r2](https://reviewable.io/reviews/necodeIT/lb_planner/56#-NjInLHZ4HGmvrMfGU9x:-NjInLHZ4HGmvrMfGU9y:b-220jt8) ([raw file](https://github.com/necodeIT/lb_planner/blob/78652c056132cd9407b6b7a9efa5e0deb9f34700/lbplanner/classes/helpers/plan_helper.php#L126)):*
> ```PHP
>         global $DB;
> 
>         $field = $DB->get_field(
> ```

did you test this. Moodles DB access does weird stuff sometimes.

**Comment by Riedlers-sockpuppet** [comment]
woe be me
branch be rebase

**Review by Riedlers-sockpuppet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/56)* status: 18 of 27 files reviewed, 1 unresolved discussion (waiting on @mcquenji and @mkocagoel)

___
*[`lbplanner/classes/helpers/plan_helper.php` line 126 at r2](https://reviewable.io/reviews/necodeIT/lb_planner/56#-NjInLHZ4HGmvrMfGU9x:-NjJG3Ui30Q3aP4BPwid:bn81ab7) ([raw file](https://github.com/necodeIT/lb_planner/blob/78652c056132cd9407b6b7a9efa5e0deb9f34700/lbplanner/classes/helpers/plan_helper.php#L126)):*
<details><summary><i>Previously, mkocagoel (Muhi) wrote…</i></summary><blockquote>

did you test this. Moodles DB access does weird stuff sometimes.
</blockquote></details>

I didn't change it

**Review by mcquenji — CHANGES_REQUESTED** [review]
I don't think you've cleaned up everything. we'll have a chat bout it tomorrow

> Reviewed 1 of 25 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/56#-:-NjdM7ky3mzg2-XUbObt:b88b5tt)* status: all files reviewed, 1 unresolved discussion (waiting on @mkocagoel)

___
*[`lbplanner/classes/helpers/plan_helper.php` line 126 at r2](https://reviewable.io/reviews/necodeIT/lb_planner/56#-NjInLHZ4HGmvrMfGU9x:-NjdNV17EVIKOGe1krGl:brcew7s) ([raw file](https://github.com/necodeIT/lb_planner/blob/78652c056132cd9407b6b7a9efa5e0deb9f34700/lbplanner/classes/helpers/plan_helper.php#L126)):*
<details><summary><i>Previously, Riedlers-sockpuppet (Riedler's Sockpuppet) wrote…</i></summary><blockquote>

I didn't change it
</blockquote></details>

@mkocagoel u trippin balls or smth?

**Review by mcquenji — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/56#-:-Njgk_636SfNH0L3wEk-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkocagoel)

**Review by Muhiiii — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/56#-:-NjgmRdL-otgKyb1uIbR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Riedlers-sockpuppet)

**Pull request merged**
