### PR TITLE
LP-208: fix remaining CI errors

### PR DESCRIPTION
**Pull request by RiedleroD**
WIP: stalled by https://github.com/necodeIT/lb_planner/pull/63

- - -
This change is [Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/72)

### CODE REVIEW

**Comment by RiedleroD** [comment]
it's still not working. what the fuck?

**Comment by mcquenji** [comment]
i honnestly do not know why the workflow is not running.
image

**Comment by RiedleroD** [comment]
milestone reached: the code checker stopped complaining ^^

now for the phpdoc checker… I need a drink 💀

**Review by mcquenji — DISMISSED** [review]
:lgtm: from my side

not my cup of tea

> Reviewed 4 of 11 files at r1, 13 of 16 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/72#-:-NpLHhAZ6BzIM7Zua0DG:boejj2r)* status: 23 of 24 files reviewed, all discussions resolved (waiting on @RiedleroD)

**Comment by RiedleroD** [comment]
bro it's not even done lol

**Review by mcquenji — COMMENTED** [review]
yeah but comforting the CI is @mkocagoel job to oversee not mine, so....  🤷

> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/72#-:-NpLJDN5EZwwjhdLaB_j:bhcrwgo)* status: 23 of 24 files reviewed, all discussions resolved (waiting on @RiedleroD)

**Comment by RiedleroD** [comment]
YESS FINALLY

**Review by Muhiiii — APPROVED** [review]
:lgtm_strong: 

> Reviewed 4 of 11 files at r1, 12 of 16 files at r2, 7 of 7 files at r3, 6 of 11 files at r6, 14 of 40 files at r7, 28 of 28 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/72#-:-NqCyjEMBs1Q6M2lzce-:bfan6fa)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mcquenji)

**Pull request merged**
