### PR TITLE
combined update_deadline and add_deadline into set_deadline

### PR DESCRIPTION
**Pull request by RiedleroD**
note: requires action from @mcquenji and/or @cpolat-tgm (the front-end team) to change the API usage

This change is [Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/70)

### CODE REVIEW

**Review by mcquenji — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/70)* status: all files reviewed, 3 unresolved discussions (waiting on @mkocagoel and @RiedleroD)

___
*[`lbplanner/services/plan/set_deadline.php` line 32 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/70#-NpKtH162LdwYCDcA3S3:-NpKtH162LdwYCDcA3S4:b-79ee9t) ([raw file](https://github.com/necodeIT/lb_planner/blob/5e7387874533267d199f04e441b08c7c689303c8/lbplanner/services/plan/set_deadline.php#L32)):*
> ```PHP
>             'moduleid' => new external_value(
>                 PARAM_INT,
>                 'The ID of the Module',
> ```

the id of the module the deadline is for
___
*[`lbplanner/services/plan/set_deadline.php` line 39 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/70#-NpKtC306vKMz1L753TU:-NpKtC306vKMz1L753TV:b8fhyn1) ([raw file](https://github.com/necodeIT/lb_planner/blob/5e7387874533267d199f04e441b08c7c689303c8/lbplanner/services/plan/set_deadline.php#L39)):*
> ```PHP
>             'deadlinestart' => new external_value(
>                 PARAM_INT,
>                 'The start of the Module',
> ```

start of the deadline*
___
*[`lbplanner/services/plan/set_deadline.php` line 46 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/70#-NpKtEXi1jg4AX82rf5s:-NpKtEXi1jg4AX82rf5t:bqq9u2s) ([raw file](https://github.com/necodeIT/lb_planner/blob/5e7387874533267d199f04e441b08c7c689303c8/lbplanner/services/plan/set_deadline.php#L46)):*
> ```PHP
>             'deadlineend' => new external_value(
>                 PARAM_INT,
>                 'The End of the Module',
> ```

end of the deadline*

**Comment by RiedleroD** [comment]
whoops

**Review by Muhiiii — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/70#-:-NpLCiYc4A5p3X11bNcg:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @mcquenji and @RiedleroD)

___
*[`lbplanner/services/plan/set_deadline.php` line 53 at r2](https://reviewable.io/reviews/necodeIT/lb_planner/70#-NpLCN-T2zIiDOHJQBcv:-NpLCN-T2zIiDOHJQBcw:b-896nc1) ([raw file](https://github.com/necodeIT/lb_planner/blob/aa086856b0e144754c039c4c7b853907238ceddf/lbplanner/services/plan/set_deadline.php#L53)):*
> ```PHP
>         ]);
>     }
> ```

Docs?

**Review by mcquenji — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/70)* status: all files reviewed, 3 unresolved discussions (waiting on @RiedleroD)

___
*[`lbplanner/services/plan/set_deadline.php` line 46 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/70#-NpKtEXi1jg4AX82rf5s:-NpLHNow6mV14fDwz0NK:b-t1chv) ([raw file](https://github.com/necodeIT/lb_planner/blob/5e7387874533267d199f04e441b08c7c689303c8/lbplanner/services/plan/set_deadline.php#L46)):*
<details><summary><i>Previously, mcquenji (mcquenji) wrote…</i></summary><blockquote>

end of the deadline*
</blockquote></details>

`End` should be in lowercase, right?

**Comment by RiedleroD** [comment]
yes, I *suppose* this was minor spelling mistake. fixed.

**Comment by Riedlers-sockpuppet** [comment]
*[`lbplanner/services/plan/set_deadline.php` line 53 at r2](https://reviewable.io/reviews/necodeIT/lb_planner/70#-NpLCN-T2zIiDOHJQBcv:-Nq2ZZQy1aQLn36uH6bV:b-adp8ed) ([raw file](https://github.com/necodeIT/lb_planner/blob/aa086856b0e144754c039c4c7b853907238ceddf/lbplanner/services/plan/set_deadline.php#L53)):*
<details><summary><i>Previously, mkocagoel (Muhi) wrote…</i></summary><blockquote>

Docs?
</blockquote></details>

not sure if we need them there. If we do, will be fixed in #72 since this PR only merges two API calls and doesn't improve on either implementation.

**Review by mcquenji — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/70#-:-Nq2iZsQ-gKG86habOlK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mkocagoel and @RiedleroD)

**Pull request merged**
