### PR TITLE
LP-169 largely remove userid as REST parameters (Riedler edition)

### PR DESCRIPTION
**Pull request by RiedleroD**
removing userid from REST parameters where it can be inferred through  the `$USER` global. This is just the parts of the code I'm responsible for, so it's *Riedler edition* 😎 

 - [x] notifications
   - [x] get_all_notifications
   - [x] update_notifications
 - [x] feedback
   - [x] delete_feedback
   - [x] get_all_feedbacks
   - [x] get_feedback
   - [x] submit_feedback
   - [x] update_feedback
 - [x] plan
   - [x] accept_invite
   - [x] add_deadline
   - [x] clear_plan
   - [x] decline_invite
   - [x] delete_deadline
   - [x] get_access
   - [x] get_invites
   - [x] get_plan
   - [x] invite_user
   - [x] leave_plan
   - [x] remove_user
   - [x] update_access
   - [x] update_deadline
   - [x] update_invite
   - [x] update_plan

~~I'm not touching the helpers for now, mostly because #39 already does and I don't want to cause merge conflicts. This should be in a separate PR anyway, imo.~~ lol. lmao. refer to #50

- - -
This change is [Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/49)

### CODE REVIEW

**Review by Muhiiii — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/49)* status: all files reviewed, 1 unresolved discussion (waiting on @RiedleroD)

___
*[`lbplanner/services/notifications/get_all_notifications.php` line 37 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/49#-NiyR1JN7hngP3KzcZsk:-NiyR1JN7hngP3KzcZsl:b12d9g2) ([raw file](https://github.com/necodeIT/lb_planner/blob/90f3fe9e7bfea5319ad49e83cc6b0c2a24e166ed/lbplanner/services/notifications/get_all_notifications.php#L37)):*
> ```PHP
>         global $DB, $USER;
> 
>         $dbnotifications = $DB->get_records(notifications_helper::TABLE, $USER->userid);
> ```

You need `array($USER->userid)`. Check https://moodledev.io/docs/apis/core/dml#get_records .

**Comment by RiedleroD** [comment]
whoops, my bad. not sure how that mistake got made

**Review by Muhiiii — COMMENTED** [review]
I would maybe declare `$userid = $USER->userid` first because of consistency

> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/49#-:-Niyas0aEWN8oGaotjXp:b67tr4r)* status: all files reviewed, 1 unresolved discussion (waiting on @RiedleroD)

**Comment by Riedlers-sockpuppet** [comment]
*[`lbplanner/services/notifications/get_all_notifications.php` line 37 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/49#-NiyR1JN7hngP3KzcZsk:-Nj7fuvq3mcqw1Suy3o4:bb7f2mf) ([raw file](https://github.com/necodeIT/lb_planner/blob/90f3fe9e7bfea5319ad49e83cc6b0c2a24e166ed/lbplanner/services/notifications/get_all_notifications.php#L37)):*
<details><summary><i>Previously, mkocagoel (Muhi) wrote…</i></summary><blockquote>

You need `array($USER->userid)`. Check https://moodledev.io/docs/apis/core/dml#get_records .
</blockquote></details>

done

**Review by Muhiiii — COMMENTED** [review]
> Reviewed 1 of 8 files at r5, 21 of 21 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/49)* status: all files reviewed, 2 unresolved discussions (waiting on @mcquenji and @RiedleroD)

___
*[`lbplanner/services/plan/decline_invite.php` line 57 at r6](https://reviewable.io/reviews/necodeIT/lb_planner/49#-Nj9jZNECNyEs5OSpe4h:-Nj9jZNECNyEs5OSpe4i:b-7b8sef) ([raw file](https://github.com/necodeIT/lb_planner/blob/461bf7681c64d53cb2d37cef9180b6aa0266ce68/lbplanner/services/plan/decline_invite.php#L57)):*
> ```PHP
>         );
> 
>         if ($invite->status === PLAN_INVITE_STATE::PENDING->value) {
> ```

What is the purpose of this statement?
___
*[`lbplanner/services/plan/invite_user.php` line 87 at r6](https://reviewable.io/reviews/necodeIT/lb_planner/49#-Nj9kV0sAubECKqplv2W:-Nj9kV0sAubECKqplv2X:b12xi0l) ([raw file](https://github.com/necodeIT/lb_planner/blob/7171efd0f46366517e206506db6bb4dc68c8dedd/lbplanner/services/plan/invite_user.php#L87)):*
> ```PHP
> 
>         $invitee = user_helper::get_mdl_user_info($inviteeid);
>         $inviter = user_helper::get_mdl_user_info($inviterid);
> ```

I know that the check doesnt work. Did you remove it so we can implement it later?

**Review by Riedlers-sockpuppet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/49)* status: all files reviewed, 2 unresolved discussions (waiting on @mcquenji and @mkocagoel)

___
*[`lbplanner/services/plan/decline_invite.php` line 57 at r6](https://reviewable.io/reviews/necodeIT/lb_planner/49#-Nj9jZNECNyEs5OSpe4h:-NjHLdrV5LFVCtm8Q4rl:blky6tq) ([raw file](https://github.com/necodeIT/lb_planner/blob/461bf7681c64d53cb2d37cef9180b6aa0266ce68/lbplanner/services/plan/decline_invite.php#L57)):*
<details><summary><i>Previously, mkocagoel (Muhi) wrote…</i></summary><blockquote>

What is the purpose of this statement?
</blockquote></details>

it's just the previous behaviour, rewritten a bit.

and I'm realizing I fucked up and this should be the exact opposite, i.e. check for whether the whether the invite *isn't* pending.
___
*[`lbplanner/services/plan/invite_user.php` line 87 at r6](https://reviewable.io/reviews/necodeIT/lb_planner/49#-Nj9kV0sAubECKqplv2W:-NjHL2rN1RPRDEtIUG6-:bfc3ccv) ([raw file](https://github.com/necodeIT/lb_planner/blob/7171efd0f46366517e206506db6bb4dc68c8dedd/lbplanner/services/plan/invite_user.php#L87)):*
<details><summary><i>Previously, mkocagoel (Muhi) wrote…</i></summary><blockquote>

I know that the check doesnt work. Did you remove it so we can implement it later?
</blockquote></details>

I removed it because it doesn't make sense to check for it anyway. If people from different classes invite each other to their plan, that's not our problem. Certainly some classes have the same modules, and overarching friendships, so this shouldn't be disabled. I talked with @mcquenji about it and he agreed to just remove this.

**Comment by Riedlers-sockpuppet** [comment]
*[`lbplanner/services/plan/decline_invite.php` line 57 at r6](https://reviewable.io/reviews/necodeIT/lb_planner/49#-Nj9jZNECNyEs5OSpe4h:-NjHMc7I7yB8AmMl_H9b:b-d3oq32) ([raw file](https://github.com/necodeIT/lb_planner/blob/461bf7681c64d53cb2d37cef9180b6aa0266ce68/lbplanner/services/plan/decline_invite.php#L57)):*
<details><summary><i>Previously, Riedlers-sockpuppet (Riedler's Sockpuppet) wrote…</i></summary><blockquote>

it's just the previous behaviour, rewritten a bit.

and I'm realizing I fucked up and this should be the exact opposite, i.e. check for whether the whether the invite *isn't* pending.
</blockquote></details>

to be clear, this checks whether the invite has already been accepted or declined

**Comment by Riedlers-sockpuppet** [comment]
yayy ✨ another force-push because github can't handle rebase properly 🥰 I love github, it's such a perfect website

**Review by mcquenji — APPROVED** [review]
:lgtm: *

*only reviewed changes directly concerning API output

> Reviewed 1 of 8 files at r5, 21 of 21 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/49#-:-NjIneke3F3IDSkEpgLl:biye0v0)* status: all files reviewed, 2 unresolved discussions (waiting on @mkocagoel)

**Review by Muhiiii — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RiedleroD)

**Pull request merged**
