### PR TITLE
LP-184 refactor courses webservices

### PR DESCRIPTION
**Pull request by Muhiiii**
Reworked Courses and removed unnecessary code. Added Docs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61)

### CODE REVIEW

**Review by mcquenji — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61)* status: all files reviewed, 2 unresolved discussions (waiting on @mkocagoel and @Riedlers-sockpuppet)

___
*[`lbplanner/services/courses/get_course.php` line 35 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/61#-Njl5vZ0Cr-NyEYIKk7h:-Njl5vZ0Cr-NyEYIKk7i:b-23s2fv) ([raw file](https://github.com/necodeIT/lb_planner/blob/ff4bb04e1d9927ce1eca8156519745526ec5e63a/lbplanner/services/courses/get_course.php#L35)):*
> ```PHP
>  * @license http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
>  */
> class courses_get_course extends external_api {
> ```

unused by frontend, can delete
___
*[`lbplanner/services/courses/update_course.php` line 42 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/61#-Njl65pu0tRClGD5upsa:-Njl65pu0tRClGD5upsb:b-2rtp40) ([raw file](https://github.com/necodeIT/lb_planner/blob/ff4bb04e1d9927ce1eca8156519745526ec5e63a/lbplanner/services/courses/update_course.php#L42)):*
> ```PHP
>         return new external_function_parameters([
>             'courseid' => new external_value(PARAM_INT, 'The id of the course', VALUE_REQUIRED, null, NULL_NOT_ALLOWED),
>             'color' => new external_value(PARAM_TEXT, 'The color of the course', VALUE_DEFAULT, null),
> ```

maybe specify which format the color has to be in. ig it's hex, but still, would be nice :)

**Review by Muhiiii — COMMENTED** [review]
LGTY?

> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61#-:-NjlGiH76W0po9XCQrgS:b-85i5t2)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @mcquenji and @Riedlers-sockpuppet)

___
*[`lbplanner/services/courses/get_course.php` line 35 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/61#-Njl5vZ0Cr-NyEYIKk7h:-NjlFXeiDY5GuLzxBwkH:b75k33n) ([raw file](https://github.com/necodeIT/lb_planner/blob/ff4bb04e1d9927ce1eca8156519745526ec5e63a/lbplanner/services/courses/get_course.php#L35)):*
<details><summary><i>Previously, mcquenji (mcquenji) wrote…</i></summary><blockquote>

unused by frontend, can delete
</blockquote></details>

Will delete the function in this PR. Due to future conflicts i will remove it from services.php in another PR
___
*[`lbplanner/services/courses/update_course.php` line 42 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/61#-Njl65pu0tRClGD5upsa:-NjlGOwOAjGXpDM7Lg7a:b-896fix) ([raw file](https://github.com/necodeIT/lb_planner/blob/ff4bb04e1d9927ce1eca8156519745526ec5e63a/lbplanner/services/courses/update_course.php#L42)):*
<details><summary><i>Previously, mcquenji (mcquenji) wrote…</i></summary><blockquote>

maybe specify which format the color has to be in. ig it's hex, but still, would be nice :)
</blockquote></details>

Done.

**Review by mcquenji — DISMISSED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61#-:-NjlMrUuBtdQJdV8YKWx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Riedlers-sockpuppet)

**Review by Riedlers-sockpuppet — CHANGES_REQUESTED** [review]
only nitpicks, seems good overall

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61#-:-NjlkOUm8Sy7x351-NZb:bczxkvh)* status: all files reviewed, 2 unresolved discussions (waiting on @mkocagoel)

___
*[`lbplanner/services/courses/update_course.php` line 83 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/61#-NjliFzq-AdReP0ahtsJ:-NjliFzq-AdReP0ahtsK:bwp4w00) ([raw file](https://github.com/necodeIT/lb_planner/blob/ff4bb04e1d9927ce1eca8156519745526ec5e63a/lbplanner/services/courses/update_course.php#L83)):*
> ```PHP
>         $course = course_helper::get_lbplanner_course($courseid, $USER->id);
> 
>         if (!is_null($color)) {
> ```

I'd replace these with `$var !== null` for readability. They do exactly the same thing.
___
*[`lbplanner/services/courses/update_course.php` line 100 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/61#-Njlj6mt3lUFTgnfwvzM:-Njlj6mt3lUFTgnfwvzN:bqgvqep) ([raw file](https://github.com/necodeIT/lb_planner/blob/ff4bb04e1d9927ce1eca8156519745526ec5e63a/lbplanner/services/courses/update_course.php#L100)):*
> ```PHP
>      * Returns nothing.
>      * @return null
>      */
> ```

do we need comments for these? Seems like wasted worktime; if the codesniffer enforces this (I'm unaware whether it does) we should look into turning that off, if possible. Same goes for all the other block comments on API structures.

**Review by Muhiiii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @mcquenji and @Riedlers-sockpuppet)

___
*[`lbplanner/services/courses/update_course.php` line 83 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/61#-NjliFzq-AdReP0ahtsJ:-NjllzS58urYyJyuGaAI:b421tbd) ([raw file](https://github.com/necodeIT/lb_planner/blob/ff4bb04e1d9927ce1eca8156519745526ec5e63a/lbplanner/services/courses/update_course.php#L83)):*
<details><summary><i>Previously, Riedlers-sockpuppet (Riedler's Sockpuppet) wrote…</i></summary><blockquote>

I'd replace these with `$var !== null` for readability. They do exactly the same thing.
</blockquote></details>

No, i would like to let it stay that way.
___
*[`lbplanner/services/courses/update_course.php` line 100 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/61#-Njlj6mt3lUFTgnfwvzM:-Njllbw892Fm4NPF9DlB:b-ri3sdh) ([raw file](https://github.com/necodeIT/lb_planner/blob/ff4bb04e1d9927ce1eca8156519745526ec5e63a/lbplanner/services/courses/update_course.php#L100)):*
<details><summary><i>Previously, Riedlers-sockpuppet (Riedler's Sockpuppet) wrote…</i></summary><blockquote>

do we need comments for these? Seems like wasted worktime; if the codesniffer enforces this (I'm unaware whether it does) we should look into turning that off, if possible. Same goes for all the other block comments on API structures.
</blockquote></details>

Its a must have from moodle.

**Review by Muhiiii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @mcquenji and @Riedlers-sockpuppet)

___
*[`lbplanner/services/courses/update_course.php` line 83 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/61#-NjliFzq-AdReP0ahtsJ:-Njln0unDs8VMRKz-co5:b5xyfbf) ([raw file](https://github.com/necodeIT/lb_planner/blob/ff4bb04e1d9927ce1eca8156519745526ec5e63a/lbplanner/services/courses/update_course.php#L83)):*
<details><summary><i>Previously, mkocagoel (Muhi) wrote…</i></summary><blockquote>

No, i would like to let it stay that way.
</blockquote></details>

nvm, changed it

**Review by Riedlers-sockpuppet — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @mcquenji)

**Review by Riedlers-sockpuppet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mcquenji and @mkocagoel)

___
*[`lbplanner/services/courses/update_course.php` line 33 at r4](https://reviewable.io/reviews/necodeIT/lb_planner/61#-NjlsEtG-ShGMKdjvkuG:-NjlsEtG-ShGMKdjvkuH:b-kezno9) ([raw file](https://github.com/necodeIT/lb_planner/blob/405acb0ac4b763755d8b38caabb8188d6cc786ea/lbplanner/services/courses/update_course.php#L33)):*
> ```PHP
>  * @package local_lbplanner
>  * @license http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
>  * @copyright 2023 ecodeIT
> ```

ecodeIT?

**Review by Muhiiii — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @mcquenji and @Riedlers-sockpuppet)

___
*[`lbplanner/services/courses/update_course.php` line 33 at r4](https://reviewable.io/reviews/necodeIT/lb_planner/61#-NjlsEtG-ShGMKdjvkuG:-Njm4UfWD6TKYHuVd-iQ:b-896fix) ([raw file](https://github.com/necodeIT/lb_planner/blob/405acb0ac4b763755d8b38caabb8188d6cc786ea/lbplanner/services/courses/update_course.php#L33)):*
<details><summary><i>Previously, Riedlers-sockpuppet (Riedler's Sockpuppet) wrote…</i></summary><blockquote>

ecodeIT?
</blockquote></details>

Done.

**Review by Muhiiii — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61)* status: all files reviewed, 1 unresolved discussion (waiting on @Riedlers-sockpuppet)

**Review by Riedlers-sockpuppet — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkocagoel)

**Review by mcquenji — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/61#-:-NjrfOiJ8KHiQDMgmVdU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mkocagoel)

**Pull request merged**
