### PR TITLE
fix: various parsing issues

### PR DESCRIPTION
**Pull request by RiedleroD**
TODOs:
- [x] better default param value parsing
- [x] action to run docsgen to catch problems early
- [x] lower cyclomatic complexity to make LSP happy
- [x] add warn context (e.g. current service name, traceback)

- - -
This change is [Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/81)

### CODE REVIEW

**Comment by RiedleroD** [comment]
warnings are now much much nicer ^^

some simulated warnings:

image

image

image

image

**Review by mcquenji — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/81)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @RiedleroD)

___
*[`document_services.py` line 57 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/81#-O2MMG0aDOpRDGfiF-Ju:-O2MMG0bCn869LBOMZoR:b-swmcxc) ([raw file](https://github.com/necodeIT/lb_planner/blob/1400d4f6afdff5d104f0bcfed265078aaa8a3e31/document_services.py#L57)):*
> ```Python
> def explain_php_value(val: str) -> tuple[None | str | int | bool, str]:
>     SPECIAL_VALUES = {
>         "$USER->id": ("current userid", "int"),
> ```

please use `derived from token` as "literal" to from a propper sentence in the UI:

**Review by mcquenji — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/81)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @RiedleroD)

___
*[`document_services.py` line 177 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/81#-O2MaHGk8LuN5be3u_QS:-O2MaHGlCwAjbWqAiztH:b-flb7gn) ([raw file](https://github.com/necodeIT/lb_planner/blob/1400d4f6afdff5d104f0bcfed265078aaa8a3e31/document_services.py#L177)):*
> ```Python
> 
>         # Extracting and adjusting capabilities
>         capabilities = re.search(r"'capabilities' => '.*:(.*?)'", function[3])
> ```

also please leave the entire capability string. currently (for example) `local/lb_planner:student` is stripped to just `student`.

**Review by Riedlers-sockpuppet — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/81)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @mcquenji and @RiedleroD)

**Review by mcquenji — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/81#-:-O2Mn-og9t0tOLMbxbfQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RiedleroD)

**Review by mcquenji — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/81)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RiedleroD)

**Pull request merged**
