### PR TITLE
re-add moodle CI action

### PR DESCRIPTION
**Pull request by RiedleroD**
@mkocagoel managed to lose the github action, which is probably the reason for it not working

- - -
This change is [Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/59)

### CODE REVIEW

**Comment by mcquenji** [comment]
iirc the gh action is in #39

**Review by Muhiiii — DISMISSED** [review]
I wouldnt say lost. But yeah, some, problems happened.

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/59#-:-NjgpoKS1ffnwsjAKE-p:bms09nf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mcquenji)

**Review by Muhiiii — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/59#-:-Njgs6-C89oXQkBSgEW9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mcquenji)

**Review by mcquenji — CHANGES_REQUESTED** [review]
see #39 i left some feedback there for the naming of the action (https://github.com/necodeIT/lb_planner/pull/39#pullrequestreview-1710861505)

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/59#-:-Njgs2BCEnz_Z4LGtZSb:butd453)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RiedleroD)

**Review by Muhiiii — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/59#-:-NjgzGuO4VTk83rUhnY0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RiedleroD)

**Review by mcquenji — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/59#-:-Njh-rnc77pRbLR_R4PO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RiedleroD)

**Pull request merged**
