### PR TITLE
LP-195 api docs

### PR DESCRIPTION
**Pull request by RiedleroD**
fixed some docs within the moodle REST API thingy

- - -
This change is [Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/63)

### CODE REVIEW

**Review by Muhiiii — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/63)* status: all files reviewed, 4 unresolved discussions (waiting on @mcquenji and @RiedleroD)

___
*[`lbplanner/classes/helpers/plan_helper.php` line 166 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NkKrChqBdDBJSxNNtCw:-NkKrChqBdDBJSxNNtCx:b-c3g61b) ([raw file](https://github.com/necodeIT/lb_planner/blob/e7a31072182826cb6de845d36a1a294446a21a61/lbplanner/classes/helpers/plan_helper.php#L166)):*
> ```PHP
> 
>         foreach ($dbdeadlines as $dbdeadline) {
>             $deadlines[] = array(
> ```

array has to be changed to []
___
*[`lbplanner/classes/helpers/plan_helper.php` line 211 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NkKrDqK8OlSAlgUOzVz:-NkKrDqK8OlSAlgUOzW-:b-c3g61b) ([raw file](https://github.com/necodeIT/lb_planner/blob/e7a31072182826cb6de845d36a1a294446a21a61/lbplanner/classes/helpers/plan_helper.php#L211)):*
> ```PHP
>     public static function plan_structure() : external_single_structure {
>         return new external_single_structure(
>             array(
> ```

array has to be changed to []
___
*[`lbplanner/classes/helpers/plan_helper.php` line 217 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NkKr8t09Z0K8Aviskpk:-NkKr8t09Z0K8Aviskpl:b-c3g61b) ([raw file](https://github.com/necodeIT/lb_planner/blob/e7a31072182826cb6de845d36a1a294446a21a61/lbplanner/classes/helpers/plan_helper.php#L217)):*
> ```PHP
>                 'deadlines' => new external_multiple_structure(
>                     new external_single_structure(
>                         array(
> ```

array has to be changed to []
___
*[`lbplanner/classes/helpers/plan_helper.php` line 258 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NkKrH_k4R7aLmWCuNHA:-NkKrH_k4R7aLmWCuNHB:b-64zate) ([raw file](https://github.com/necodeIT/lb_planner/blob/e7a31072182826cb6de845d36a1a294446a21a61/lbplanner/classes/helpers/plan_helper.php#L258)):*
> ```PHP
>         foreach ($deadlines as $deadline) {
>             $deadline['planid'] = $newplanid;
>             $DB->insert_record(self::DEADLINES_TABLE, $deadline);
> ```

pls test first.

**Comment by Riedlers-sockpuppet** [comment]
*[`lbplanner/classes/helpers/plan_helper.php` line 166 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NkKrChqBdDBJSxNNtCw:-NkKtS1M8m4mjoKGOpXM:b-uxfuy4) ([raw file](https://github.com/necodeIT/lb_planner/blob/e7a31072182826cb6de845d36a1a294446a21a61/lbplanner/classes/helpers/plan_helper.php#L166)):*
<details><summary><i>Previously, mkocagoel (Muhi) wrote…</i></summary><blockquote>

array has to be changed to []
</blockquote></details>

the arrays will be changed to [] in another PR

**Review by mcquenji — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/63)* status: all files reviewed, 6 unresolved discussions (waiting on @mkocagoel and @RiedleroD)

___
*[`lbplanner/classes/helpers/plan_helper.php` line 219 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NkLBCrT4Y6ZqUo9sF9I:-NkLBCrT4Y6ZqUo9sF9J:b-t30zh8) ([raw file](https://github.com/necodeIT/lb_planner/blob/e7a31072182826cb6de845d36a1a294446a21a61/lbplanner/classes/helpers/plan_helper.php#L219)):*
> ```PHP
>                         array(
>                             'moduleid' => new external_value(PARAM_INT, 'ID of the module'),
>                             'deadlinestart' => new external_value(PARAM_INT, 'Start of the Deadline'),
> ```

add that this is a Unix timestamp or whatever it is
___
*[`lbplanner/classes/helpers/plan_helper.php` line 220 at r1](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NkL7J1AEBT6VWKlyOm5:-NkL7J1AEBT6VWKlyOm6:b13n9be) ([raw file](https://github.com/necodeIT/lb_planner/blob/e7a31072182826cb6de845d36a1a294446a21a61/lbplanner/classes/helpers/plan_helper.php#L220)):*
> ```PHP
>                             'moduleid' => new external_value(PARAM_INT, 'ID of the module'),
>                             'deadlinestart' => new external_value(PARAM_INT, 'Start of the Deadline'),
>                             'deadlineend' => new external_value(PARAM_INT, 'The id of the user'),
> ```

`deadlineend` does not sound like it's the ID of the user

**Review by mcquenji — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/63)* status: 15 of 16 files reviewed, 5 unresolved discussions (waiting on @mkocagoel and @RiedleroD)

___
*[`lbplanner/classes/helpers/plan_helper.php` line 228 at r2](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NkZmLVk8xSc9m9j4hh9:-NkZmLVk8xSc9m9j4hhA:b7ir5s2) ([raw file](https://github.com/necodeIT/lb_planner/blob/f689df5bba9d47c20a74215c01b3bf319070554a/lbplanner/classes/helpers/plan_helper.php#L228)):*
> ```PHP
>                         array(
>                             'userid' => new external_value(PARAM_INT, 'The id of the user'),
>                             'accesstype' => new external_value(PARAM_INT, 'The role of the user'),
> ```

please add the possible types & values to the docs

**Review by mcquenji — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/63)* status: all files reviewed, 6 unresolved discussions (waiting on @mkocagoel and @RiedleroD)

___
*[`lbplanner/classes/helpers/notifications_helper.php` line 80 at r3](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NmbIj4KDVrf_TLBUD2z:-NmbIj4KDVrf_TLBUD3-:bq12w8q) ([raw file](https://github.com/necodeIT/lb_planner/blob/c6b0debffb0949ed260aa3f0079b99fc2c16a319/lbplanner/classes/helpers/notifications_helper.php#L80)):*
> ```PHP
>             'courseid' => new external_value(PARAM_INT, 'course ID'),
>             'status' => new external_value(PARAM_INT, 'module status (pending, late, uploaded, done)'),
>             'type' => new external_value(PARAM_INT, 'module type (GK/EK)'),
> ```

please also add the integer values
___
*[`lbplanner/services/plan/accept_invite.php` line 28 at r3](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NmbJR7TBurINGR79PnN:-NmbJR7TBurINGR79PnO:b-lhmqkx) ([raw file](https://github.com/necodeIT/lb_planner/blob/c6b0debffb0949ed260aa3f0079b99fc2c16a319/lbplanner/services/plan/accept_invite.php#L28)):*
> ```PHP
> 
> /**
>  * Accept an invite from the plan.
> ```

I'd use: "[...] to the plan"

**Comment by RiedleroD** [comment]
I've re-reviewed this myself again and it seems I did a bit of bullshit. oops!

the stuff in `lbplanner/classes/helpers/notifications_helper.php` should be regarding a notification, not a module. The module structure is already defined in ``lbplanner/classes/helpers/modules_helper.php`, though I still need to add enum specs there as well :/

**Review by mcquenji — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/63)* status: 20 of 21 files reviewed, 8 unresolved discussions (waiting on @mkocagoel and @RiedleroD)

___
*[`lbplanner/classes/helpers/modules_helper.php` line 111 at r4](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NpKuaDZ1sOtqyAQlPZ6:-NpKuaD_3WvYBDrGZzSG:b1bpww0) ([raw file](https://github.com/necodeIT/lb_planner/blob/c977f0fb58ae91cab1841b08cd959de5e28af2c7/lbplanner/classes/helpers/modules_helper.php#L111)):*
> ```PHP
>         array(
>             'moduleid' => new external_value(PARAM_INT, 'Module ID'),
>             'name' => new external_value(PARAM_TEXT, 'Module name'),
> ```

iirc this is the short name of the module. please also add that the name is 5 characters max.
___
*[`lbplanner/classes/helpers/modules_helper.php` line 116 at r4](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NpKuzvz4UTXd30UnRoe:-NpKuzvz4UTXd30UnRof:b2c8l7) ([raw file](https://github.com/necodeIT/lb_planner/blob/c977f0fb58ae91cab1841b08cd959de5e28af2c7/lbplanner/classes/helpers/modules_helper.php#L116)):*
> ```PHP
>             'type' => new external_value(PARAM_INT, 'Module type '.MODULE_TYPE::format()),
>             'url' => new external_value(PARAM_TEXT, 'URL to moodle page for module'),
>             'grade' => new external_value(PARAM_INT, 'The grade of the module '.MODULE_GRADE::format()),
> ```

please talk with @mkocagoel about the grade data type. If I'm up to date we can't express the grade in a simple enum as every teacher uses a different scale, so it would be best to simply return a string.

**Review by Muhiiii — DISMISSED** [review]
:lgtm:

> Reviewed 1 of 10 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/63#-:-NpLESd6ERSxYXym0v5G:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @mcquenji and @RiedleroD)

___
*[`lbplanner/classes/helpers/modules_helper.php` line 116 at r4](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NpKuzvz4UTXd30UnRoe:-NpLDsfgCiyN4Oec3SGv:b-8521e4) ([raw file](https://github.com/necodeIT/lb_planner/blob/c977f0fb58ae91cab1841b08cd959de5e28af2c7/lbplanner/classes/helpers/modules_helper.php#L116)):*
<details><summary><i>Previously, mcquenji (mcquenji) wrote…</i></summary><blockquote>

please talk with @mkocagoel about the grade data type. If I'm up to date we can't express the grade in a simple enum as every teacher uses a different scale, so it would be best to simply return a string.
</blockquote></details>

Yes, Boolean + String

**Review by mcquenji — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/63)* status: all files reviewed, 2 unresolved discussions (waiting on @mkocagoel and @RiedleroD)

___
*[`lbplanner/classes/helpers/modules_helper.php` line 116 at r4](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NpKuzvz4UTXd30UnRoe:-NpLGtAtB91t6eCktjlG:b-gry1lt) ([raw file](https://github.com/necodeIT/lb_planner/blob/c977f0fb58ae91cab1841b08cd959de5e28af2c7/lbplanner/classes/helpers/modules_helper.php#L116)):*
<details><summary><i>Previously, mkocagoel (Muhi) wrote…</i></summary><blockquote>

Yes, Boolean + String
</blockquote></details>

is this going to be addressed in another pr?

**Comment by Riedlers-sockpuppet** [comment]
*[`lbplanner/classes/helpers/modules_helper.php` line 116 at r4](https://reviewable.io/reviews/necodeIT/lb_planner/63#-NpKuzvz4UTXd30UnRoe:-Nq2_9SECxeOyQmiK38N:b-4qmfpy) ([raw file](https://github.com/necodeIT/lb_planner/blob/c977f0fb58ae91cab1841b08cd959de5e28af2c7/lbplanner/classes/helpers/modules_helper.php#L116)):*
<details><summary><i>Previously, mcquenji (mcquenji) wrote…</i></summary><blockquote>

is this going to be addressed in another pr?
</blockquote></details>

yes. @mkocagoel is responsible for the module subservice, so I've actually done what's supposed to be his work here anyway >;)

no but I've decided it's easier fixing *all* the docs at once than to check what's my obligation and what isn't. This part though is implementation, not documentation, so it should be a different PR anyway.

**Review by mcquenji — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/necodeIT/lb_planner/63#-:-Nq2i9BcEmgIiKyKZP4R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RiedleroD)

**Pull request merged**
